org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties

minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
forge_version=52.1.0
forge_version_range=[0,)
loader_version_range=[0,)
mapping_channel=parchment
mapping_version=2024.11.17-1.21.1

## Mod Properties

mod_id=ptw
mod_name=Paving The Way
mod_license=ARR(All Rights Reserved)
mod_version=1.2.0-mc+1.21.1-forge
mod_group_id=com.butteredapples.ptw
mod_authors=ButteredApples
mod_description=Adds more path blocks to the game.